import { Product, Service, Review, PortfolioItem, FAQItem } from './types';

export const COMP_STATS = [
  { label: 'Years Experience', value: 10, suffix: '+' },
  { label: 'Happy Customers', value: 5000, suffix: '+' },
  { label: 'Mobile Brands', value: 100, suffix: '+' },
  { label: 'Support SLA', value: 24, suffix: '/7' },
];

export const FEATURED_BRANDS = [
  { name: 'Apple', logo: '🍎', description: 'Experience the pinnacle of innovation and luxury.' },
  { name: 'Samsung', logo: '📱', description: 'Pioneering future-forward screens and AI power.' },
  { name: 'OnePlus', logo: '🚀', description: 'Never Settle with flagship speed and fluid UI.' },
  { name: 'Xiaomi', logo: '🔋', description: 'Smart living, extreme value, and Leica camera optics.' },
  { name: 'Vivo', logo: '📸', description: 'Professional studio-grade portraits at your fingertips.' },
  { name: 'Oppo', logo: '💎', description: 'Gorgeous designs combined with superfast flash charge.' },
  { name: 'Realme', logo: '💛', description: 'Challenging the status-quo with leap-forward camera and design.' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    description: 'Forged in titanium, featuring the groundbreaking A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever.',
    price: 139900,
    originalPrice: 154900,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    badge: 'Flagship Leader',
    specs: ['Super Retina XDR OLED', 'A17 Pro 3nm Chip', '5x Telephoto Zoom', 'Grade-5 Titanium Frame'],
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    description: 'Empowered by Galaxy AI. Take stunning dusk-to-dawn shots with custom Nightography, translate live conversations, and write with built-in S-Pen.',
    price: 129999,
    originalPrice: 139999,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'AI Powered',
    specs: ['Dynamic AMOLED 2X 120Hz', 'Snapdragon 8 Gen 3', '200MP Quad Camera', 'Embedded S-Pen'],
    inStock: true,
  },
  {
    id: 'p3',
    name: 'OnePlus 12 Dual-SIM',
    brand: 'OnePlus',
    description: 'Redefining smooth efficiency. Features 100W SUPERVOOC charging, highly advanced Hasselblad Camera for Mobile, and Dual Cryo-velocity Cooling.',
    price: 64999,
    originalPrice: 69999,
    image: 'https://images.unsplash.com/photo-1565630916779-e303be97b6f5?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    badge: '100W SuperVOOC',
    specs: ['2K 120Hz ProXDR Display', 'Snapdragon 8 Gen 3', 'Hasselblad Camera Co-op', '5400mAh High-Density Battery'],
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Xiaomi 14 Ultra',
    brand: 'Xiaomi',
    description: 'Co-engineered with Leica. Integrates 1-inch sensor, stepless variable aperture, and liquid-cool loops inside an elegant vegan leather backing.',
    price: 99999,
    originalPrice: 119999,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'Leica Optics',
    specs: ['All-Around Liquid Display', 'Leica Quad Camera', 'Snapdragon 8 Gen 3', '90W HyperCharge Wireless'],
    inStock: false,
  },
  {
    id: 'p5',
    name: 'Vivo X100 Pro',
    brand: 'Vivo',
    description: 'Zeiss APO Floating Telephoto camera designed for exquisite color grading and extreme detail. Features Dimensity 9300 for buttery peak performance.',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: 'Zeiss Certified',
    specs: ['Zeiss T* Anti-Reflective Coating', 'Dimensity 9300 Chipset', '5400mAh BlueVolt Battery', 'V3 Imaging Chip'],
    inStock: true,
  },
  {
    id: 'p6',
    name: 'Oppo Find X7 Ultra',
    brand: 'Oppo',
    description: 'The world\'s first dual-periscope camera setup, backed by Hasselblad Master Tuned Portrait engine and beautiful hand-crafted premium chassis.',
    price: 74999,
    originalPrice: 79999,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    badge: 'Dual Periscope',
    specs: ['Ultra-bright Diamond Screen', 'Snapdragon 8 Gen 3', 'Hasselblad Portrait Mode', 'IP68 Water Resistant'],
    inStock: true,
  },
  {
    id: 'p7',
    name: 'iPhone 15 Plus',
    brand: 'Apple',
    description: 'Dynamic Island floats your alerts, a durable color-infused back glass design, and a spectacular 48MP main camera with comfortable hand-feel.',
    price: 84900,
    originalPrice: 89900,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    specs: ['Dynamic Island Display', 'A16 Bionic Processor', '2x Telephoto Optical Crop', 'Outstanding Battery Life'],
    inStock: true,
  },
  {
    id: 'p8',
    name: 'Galaxy S24+ FE',
    brand: 'Samsung',
    description: 'All premium features packed inside a slim high-durability frame, focusing on modern creative styling and unmatched multitasking controls.',
    price: 59999,
    originalPrice: 64999,
    image: 'https://images.unsplash.com/photo-1610945415295-d9bff067e59c?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    badge: 'Popular Choice',
    specs: ['6.7" Dynamic AMOLED', 'Exynos 2400 Deca-Core', '50MP triple adaptive camera', '4700mAh battery'],
    inStock: true,
  },
  {
    id: 'p9',
    name: 'iPhone 15',
    brand: 'Apple',
    description: 'Featuring the amazing Dynamic Island, custom 48MP primary sensor, high-density colors embedded into durable rear glass, and high-speed USB-C connector.',
    price: 69905,
    originalPrice: 79900,
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    specs: ['6.1" Super Retina display', 'Dynamic Island notifications', 'A16 Bionic computing', 'Ceramic Shield protection'],
    inStock: true,
  },
  {
    id: 'p10',
    name: 'iPad Pro 11" M4',
    brand: 'Apple',
    description: 'The thinnest Apple product ever, housing the next-generation M4 chip, groundbreaking tandem OLED Ultra Retina XDR display, and stunning GPU performance.',
    price: 99900,
    originalPrice: 109900,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    badge: 'M4 Superchip',
    specs: ['Tandem OLED Display', 'Apple M4 Processor', '120Hz ProMotion engine', 'Pro camera + LiDAR sensor'],
    inStock: true,
  },
  {
    id: 'p11',
    name: 'Galaxy Z Fold 6',
    brand: 'Samsung',
    description: 'The ultimate multitasking machine. Fold it for a slim handheld, or open to a cinematic mini-tablet equipped with premium ARM power and Galaxy AI.',
    price: 164999,
    originalPrice: 174999,
    image: 'https://images.unsplash.com/photo-1583573636246-18cb2246697f?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'Foldable Flagship',
    specs: ['7.6" Main Foldable AMOLED', 'Snapdragon 8 Gen 3 for Galaxy', 'FlexMode Hinge Armor', 'Circle to Search ready'],
    inStock: true,
  },
  {
    id: 'p12',
    name: 'Galaxy A55 5G',
    brand: 'Samsung',
    description: 'Experience premium style with a metal frame, vibrant AMOLED screen, secure Knox safety, and stunning low-light snaps for everyday life.',
    price: 39999,
    originalPrice: 42999,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=600&q=80',
    rating: 4.4,
    specs: ['6.6" 120Hz OLED screen', 'Exynos 1480 processor', '50MP camera with OIS', '5000mAh 2-day battery'],
    inStock: true,
  },
  {
    id: 'p13',
    name: 'OnePlus 12R',
    brand: 'OnePlus',
    description: 'The Performance Assassin. Merges a beautiful 120Hz 4th-gen LTPO screen, robust battery, and high-speed fast charging without breaking the bank.',
    price: 39999,
    originalPrice: 42999,
    image: 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: 'Value Beast',
    specs: ['LTPO4 AMOLED 4500 nits', 'Snapdragon 8 Gen 2', '5500mAh battery', '100W fast charger included'],
    inStock: true,
  },
  {
    id: 'p14',
    name: 'OnePlus Nord 4',
    brand: 'OnePlus',
    description: 'Durable, stylish and all-metal unibody back panel. Runs on a powerful mid-tier Snapdragon chip, boasting brilliant dual stereos for deep media focus.',
    price: 29999,
    originalPrice: 32999,
    image: 'https://images.unsplash.com/photo-1557180295-76eee20ae8aa?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    specs: ['Fluid metal unibody design', 'Snapdragon 7+ Gen 3', '50MP dual lens system', '5500mAh battery + 100W SuperVOOC'],
    inStock: true,
  },
  {
    id: 'p15',
    name: 'Xiaomi Redmi Note 13 Pro+ 5G',
    brand: 'Xiaomi',
    description: 'Stunning curved design paired with an elite 200MP camera system. Offers extreme 120W HyperCharge powering your day in just 19 minutes.',
    price: 31999,
    originalPrice: 33999,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: '200MP Camera',
    specs: ['1.5K 120Hz Curved AMOLED', '200MP OIS Elite Sensor', 'Dimensity 7200-Ultra', '120W HyperCharge Brick'],
    inStock: true,
  },
  {
    id: 'p16',
    name: 'POCO F6 Pro',
    brand: 'Xiaomi',
    description: 'Hyper-powered gaming champion. Incorporates Snapdragon 8 Gen 2, high density WQHD+ resolution screen, and custom gaming cooling plates.',
    price: 39999,
    originalPrice: 44999,
    image: 'https://images.unsplash.com/photo-1533228896862-ec704273c880?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    badge: 'Gaming Focus',
    specs: ['WQHD+ Flow AMOLED 120Hz', 'Snapdragon 8 Gen 2', '120W Flash Charge', 'LiquidCool Technology 4.0'],
    inStock: true,
  },
  {
    id: 'p17',
    name: 'Vivo V30 Pro',
    brand: 'Vivo',
    description: 'Crafted for unmatched studio portraits. Featuring a powerful triple camera backed by Aura Light system for shadow-free professional lighting.',
    price: 41999,
    originalPrice: 46999,
    image: 'https://images.unsplash.com/photo-1565849906461-0e25ed50def4?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    badge: 'Aura Light Tech',
    specs: ['3D Curved 120Hz Screen', 'Aura Light Studio Flash', 'MediaTek Dimensity 8200', '50MP Group Selfie camera'],
    inStock: true,
  },
  {
    id: 'p18',
    name: 'Vivo Y200 Pro 5G',
    brand: 'Vivo',
    description: 'Vibrant, high-durability modern handset boasting silky anti-fingerprint back glass, premium slim design and brilliant daily performance metrics.',
    price: 24999,
    originalPrice: 26999,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=600&q=80',
    rating: 4.3,
    specs: ['Dual Curved Display', 'Snapdragon 695 5G', '64MP OIS main camera', 'Slim design at 7.49mm'],
    inStock: true,
  },
  {
    id: 'p19',
    name: 'Oppo Reno 12 Pro',
    brand: 'Oppo',
    description: 'Elite portrait machine combining powerful custom AI Eraser toolsets, premium fluid-alloy armor frame and long-lasting heavy-duty battery arrays.',
    price: 36999,
    originalPrice: 40999,
    image: 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: 'Al Portrait',
    specs: ['Quad Curved AMOLED', 'MediaTek Dimensity 7300-Energy', 'AI LinkBoost Connectivity', '80W SUPERVOOC Charge'],
    inStock: true,
  },
  {
    id: 'p20',
    name: 'Oppo A98 5G',
    brand: 'Oppo',
    description: 'Premium everyday companion. Complete with 67W flash charging, micorlens microscopic magnify lens, and highly durable silk-weave aesthetics.',
    price: 21999,
    originalPrice: 24999,
    image: 'https://images.unsplash.com/photo-1573148195900-7845dcb9b127?auto=format&fit=crop&w=600&q=80',
    rating: 4.2,
    specs: ['120Hz Ultra Smooth Screen', '67W Flash Charge', '64MP AI Triple + MicroLens', '5000mAh Large Battery'],
    inStock: true,
  },
  {
    id: 'p21',
    name: 'Realme GT 6',
    brand: 'Realme',
    description: 'The AI flagship killer. Built with Snapdragon 8s Gen 3, a blistering 6000 nits ultra-bright display, and Next Ai capabilities for extreme workflow speed.',
    price: 40999,
    originalPrice: 44999,
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'AI Flagship Killer',
    specs: ['8s Gen 3 Flagship Processor', '6000 nits Ultra-Bright screen', '50MP Dual OIS Camera', '120W SUPERVOOC + 5500mAh'],
    inStock: true,
  },
  {
    id: 'p22',
    name: 'Realme 12 Pro+ 5G',
    brand: 'Realme',
    description: 'Exquisite design co-created with luxury watch-maker Ollivier Savéo. Houses a revolutionary 64MP periscope portrait camera.',
    price: 29999,
    originalPrice: 32999,
    image: 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    badge: 'Luxury Watch Design',
    specs: ['120Hz Curved Vision Screen', '64MP Periscope Portrait Lens', 'Snapdragon 7s Gen 2', 'Vegan Leather Styling'],
    inStock: true,
  },
  {
    id: 'p23',
    name: 'Realme C67 5G',
    brand: 'Realme',
    description: 'Unbelievable 5G value. Outfitted with high efficiency Dimensity processor, vibrant FHD+ punch hole panel and speedy 33W charge speeds.',
    price: 13999,
    originalPrice: 16999,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=600&q=80',
    rating: 4.4,
    badge: 'Best Budget 5G',
    specs: ['6.72" 120Hz display', 'MediaTek Dimensity 6100+', '50MP AI primary camera', '33W SUPERVOOC charging'],
    inStock: true,
  },
  {
    id: 'p24',
    name: 'iPhone 14',
    brand: 'Apple',
    description: 'Boasts an incredible dual-camera system, stunning crash detection features, class-leading battery, and highly durable ceramic front panel details.',
    price: 59900,
    originalPrice: 69900,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    specs: ['6.1" OLED Display', 'A15 Bionic Processor', 'Pro Camera Engine', 'Ceramic Shield Protection'],
    inStock: true,
  },
  {
    id: 'p25',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    description: 'The ultimate rugged sports timepiece. Aerospace grade titanium case, extreme battery life, ultra bright Always‑On Retina display.',
    price: 89900,
    originalPrice: 94900,
    image: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    badge: 'Sport Special',
    specs: ['Titanium 49mm Case', 'Up to 72 hours Battery', 'Dual-frequency GPS', '3000 nits display brightness'],
    inStock: true,
  },
  {
    id: 'p26',
    name: 'Galaxy S24 5G',
    brand: 'Samsung',
    description: 'Compact size with infinite premium intelligence. Enhanced AI photo editors, brilliant FHD+ screen controls and gorgeous space-grade finish.',
    price: 74999,
    originalPrice: 79999,
    image: 'https://images.unsplash.com/photo-1610945415295-d9bff067e59c?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    specs: ['6.2" Dynamic AMOLED 2X', 'Exynos 2400 Octa-Core', 'Galaxy AI Smart Editor', 'Armor Aluminum 2.0'],
    inStock: true,
  },
  {
    id: 'p27',
    name: 'Galaxy Buds3 Pro',
    brand: 'Samsung',
    description: 'High fidelity studio level audios, designed with active responsive blades, premium adaptive noise isolation and customized ear fitments.',
    price: 19999,
    originalPrice: 22999,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: 'Hi-Fi Audio',
    specs: ['24bit High Fidelity Codec', 'Blade Light LED Accents', 'Adaptive ANC & Ambient', 'Secure ergonomic grip'],
    inStock: true,
  },
  {
    id: 'p28',
    name: 'OnePlus Nord CE4 5G',
    brand: 'OnePlus',
    description: 'Superb balance of battery longevity and fluid daily power. Boasts high-efficiency processors and outstanding 100W SUPERVOOC hyper charge.',
    price: 24999,
    originalPrice: 26999,
    image: 'https://images.unsplash.com/photo-1557180295-76eee20ae8aa?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    specs: ['Snapdragon 7 Gen 3', '5500mAh Large Battery', '100W SUPERVOOC charging', 'Aqua Touch Display Ready'],
    inStock: true,
  },
  {
    id: 'p29',
    name: 'OnePlus Pad 2',
    brand: 'OnePlus',
    description: 'The thinnest full-performance tablet. Perfect productivity ratio screen, gorgeous metal backplate, paired with Snapdragon 8 Gen 3 computation.',
    price: 39999,
    originalPrice: 44999,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'Pro Tablet',
    specs: ['12.1" 3K 144Hz Display', 'Snapdragon 8 Gen 3', '6 Speakers Omnidirectional', '9510mAh + 67W charge'],
    inStock: true,
  },
  {
    id: 'p30',
    name: 'Xiaomi 14 5G',
    brand: 'Xiaomi',
    description: 'A compact optical masterwork. Customized Leica Summilux lens arrays, ultra-narrow bezel display design and blazing Snapdragon 8 Gen 3 performance.',
    price: 69999,
    originalPrice: 79999,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    badge: 'Compact Flagship',
    specs: ['Leica Summilux Camera', 'Snapdragon 8 Gen 3', '120Hz CrystalRes LTPO', 'IP68 Dust & Water Resistant'],
    inStock: true,
  },
  {
    id: 'p31',
    name: 'Redmi 13C 5G',
    brand: 'Xiaomi',
    description: 'Incredibly reliable high-durability budget 5G handset. Complete with stunning starry backplate patterns and high refresh rate smooth screen.',
    price: 10999,
    originalPrice: 13999,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=600&q=80',
    rating: 4.3,
    specs: ['MediaTek Dimensity 6100+', '50MP AI Dual Camera', 'up to 16GB Extended RAM', '5000mAh Battery'],
    inStock: true,
  },
  {
    id: 'p32',
    name: 'Vivo T3 5G',
    brand: 'Vivo',
    description: 'The Speed Vanguard. Housing rapid Sony OIS primary cameras, highly performant MediaTek computing cores, and extreme slim daily form factor.',
    price: 19999,
    originalPrice: 21999,
    image: 'https://images.unsplash.com/photo-1565849906461-0e25ed50def4?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    specs: ['MediaTek Dimensity 7200', 'Sony IMX882 OIS Camera', '120Hz AMOLED panel brightness', 'Dual Stereo Speakers'],
    inStock: true,
  },
  {
    id: 'p33',
    name: 'Vivo V40 Pro',
    brand: 'Vivo',
    description: 'The portrait specialist co-created with Zeiss. Brings studio-level lighting filters, and dual-group auto autofocus selfie features for influencers.',
    price: 49999,
    originalPrice: 54999,
    image: 'https://temperedshop.in/cdn/shop/files/3_d8f45239-ff41-4c25-86e3-0056c442ea5d.png?v=1734194999',
    rating: 4.7,
    badge: 'Zeiss Portrait Champion',
    specs: ['Zeiss Custom Optics', 'MediaTek Dimensity 9200+', '5500mAh BlueVolt Battery', '80W FlashCharge'],
    inStock: true,
  },
  {
    id: 'p34',
    name: 'Oppo Reno 12 5G',
    brand: 'Oppo',
    description: 'Beautiful fluid metal aesthetic unibody. Equipped with high class AI Smart Eraser, ultra-strong link booster antennas and supreme daily durability.',
    price: 32999,
    originalPrice: 35999,
    image: 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    specs: ['AI Portrait Retouching', 'Dimensity 7300 Octa-core', 'Waterproof anti-corrosive chassis', '80W SUPERVOOC charging'],
    inStock: true,
  },
  {
    id: 'p35',
    name: 'Oppo F27 Pro+ 5G',
    brand: 'Oppo',
    description: 'India\'s first super-rugged waterproof device with IP69 rating. Luxury leather styling and extremely durable high-density drop armor protections.',
    price: 27999,
    originalPrice: 29999,
    image: 'https://images.unsplash.com/photo-1573148195900-7845dcb9b127?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    badge: 'IP69 Super Armor',
    specs: ['IP69 Highest Waterproof rating', '360° Armor Body protection', '64MP ultra-clear camera', '67W Flash charge'],
    inStock: true,
  },
  {
    id: 'p36',
    name: 'Realme GT 6T 50G',
    brand: 'Realme',
    description: 'The absolute speed champion. Blazing performance with custom cooling vents, high capacity fast charger and stunning high refresh curved panel.',
    price: 30999,
    originalPrice: 33999,
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    specs: ['Snapdragon 7+ Gen 3', '6000 nits Ultra-Bright AMOLED', '5500mAh + 120W SUPERVOOC', 'Iceberg Vapor Cooling System'],
    inStock: true,
  },
  {
    id: 'p37',
    name: 'Realme Narzo 70 Pro',
    brand: 'Realme',
    description: 'Designed with a beautiful premium duotone glass body. Equipped with custom gesture-less swipe interfaces and stunning Sony night vision cameras.',
    price: 19999,
    originalPrice: 21999,
    image: 'https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
    badge: 'Sony Night Sensor',
    specs: ['Sony IMX890 Camera', 'Duo-Touch Glass Design', 'MediaTek Dimensity 7050', '67W SUPERVOOC Flash'],
    inStock: true,
  },
  {
    id: 'p38',
    name: 'Realme Narzo 60 5g',
    brand: 'Realme',
    description: 'Designed with a beautiful premium duotone glass body. Equipped with custom gesture-less swipe interfaces and stunning Sony night vision cameras.',
    price: 19999,
    originalPrice: 25999,
    image: 'https://m.media-amazon.com/images/I/81R6aEDK5VL._SX679_.jpg',
    rating: 4.5,
    badge: 'Sony Night Sensor',
    specs: ['Sony IMX890 Camera', 'Duo-Touch Glass Design', 'MediaTek Dimensity 7050', '67W SUPERVOOC Flash'],
    inStock: true,
  }
];

export const SERVICES: Service[] = [
  {
    id: 's1',
    title: 'Smartphone Sales',
    description: 'Curated selection of certified brand-new and pristine-grade smartphones with full direct manufacturer warranty support and instant flexible trade-ins.',
    iconName: 'Smartphone',
    longDesc: 'We are official retail partners for Apple, Samsung, OnePlus, Xiaomi, and Vivo. Our sales consultants guide you to pick the exact storage, color, and performance profile for your personal or professional usage, including full data migration setups included for free.'
  },
  {
    id: 's2',
    title: 'Mobile Repairing',
    description: 'Expert diagnostics and precision component-level dynamic repairing by Apple, Samsung, and Android certified hardware engineers.',
    iconName: 'Wrench',
    longDesc: 'From motherboard soldering to water damage reclamation, custom audio IC rectifying, and power charging port restoration. All repair operations pass comprehensive multi-point security testing before leaving our workstation.'
  },
  {
    id: 's3',
    title: 'Accessories Sales',
    description: 'Premium protection and dynamic audio add-ons including active-noise cancelling earbuds, premium shockproof cases, high-speed GaN chargers, and screen guards.',
    iconName: 'Sparkles',
    longDesc: 'We stock original premium brands like Spigen, UAG, Anker, Belkin, and native manufacturers accessories. Secure your flagship gadget with military-grade drop protections and advanced Qi2/MagSafe wireless docks.'
  },
  {
    id: 's4',
    title: 'Screen Replacement',
    description: 'Instant, certified screen restorations using genuine manufacturer-grade OLED & LCD sensory display modules under strict warranty.',
    iconName: 'SmartphoneIcon',
    longDesc: 'We perform rapid screen changes in under 45 minutes. Utilizing professional dust-free vacuum laminators and customized adhesive seals ensuring water-resistance metrics stay perfectly intact.'
  },
  {
    id: 's5',
    title: 'Software Updates',
    description: 'Comprehensive OS flashes, network profile setups, boot loop recoveries, and highly secure malware removals without losing your precious files.',
    iconName: 'Cpu',
    longDesc: 'Staging clean boot setups, addressing stubborn software black-screens, resolving slow cache delays, rendering secure firmware unlocks, and setting up cloud synchronization architectures.'
  },
  {
    id: 's6',
    title: 'Smartwatch & Gadget Sales',
    description: 'Ecosystem extensions with smartwatches, tablets, Bluetooth audio trackers, and innovative smart home companion gadgets.',
    iconName: 'Watch',
    longDesc: 'Discover high-end trackers like Apple Watch Ultra and Galaxy Watch, premium iPads and Galaxy Tabs, along with intelligent motion beacons and localized wireless transceivers.'
  },
  {
    id: 's7',
    title: 'Data Transfer Services',
    description: 'Secure, clean device migrations, WhatsApp Chat histories cross-platform syncing, and automated cloud backups.',
    iconName: 'Database',
    longDesc: 'Migrating safely from iOS to Android or vice versa. We transfer contacts, messages, photos, app configurations, and custom databases securely without leaking a single byte of your private info.'
  },
  {
    id: 's8',
    title: 'Customer Support',
    description: '24/7 dedicated troubleshooting hotline and immediate interactive remote diagnostic advice for any operational query.',
    iconName: 'Headphones',
    longDesc: 'Access continuous help from technical specialists who can verify diagnostic codes and configure mail-in repair bookings, ensuring you are never stranded without a working device.'
  }
];

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: 'pt1',
    title: 'Mobile Showroom Front',
    category: 'Showroom',
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    description: 'Our luxurious flagship physical store showroom exhibiting interactive demonstration zones.'
  },
  {
    id: 'pt2',
    title: 'Interactive Gadget Pods',
    category: 'Showroom',
    image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    description: 'Live test table hosting premium wearables, smartwatches, and flagship virtual reality accessories.'
  },
  {
    id: 'pt4',
    title: 'Customer Consultations',
    category: 'Interaction',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80',
    description: 'Our digital advocates explaining complex software and cloud capabilities to friendly local patrons.'
  },
  {
    id: 'pt5',
    title: 'Smart Tech Exhibits',
    category: 'Gadget',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    description: 'Sleek visual setup showcasing high-fidelity sound-bars and wireless noise-reduction headphones.'
  },
  {
    id: 'pt6',
    title: 'Latest Audio Devices',
    category: 'Gadget',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Bespoke custom headphone docks with live frequency response tuning capabilities.'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    name: 'Sarah Jenkins',
    role: 'Tech Reviewer & Content Creator',
    text: 'MobiSphere has been my absolute go-to for flagship device purchases for years. Their staff possesses unparalleled technological depth, helping me pick precise hardware specs. The trade-in value offered for my previous device was stellar, and the data transfer took less than 10 minutes!',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    date: 'May 12, 2026'
  },
  {
    id: 'r2',
    name: 'Michael Chen',
    role: 'Managing Director, Chen Consultants',
    text: 'Required a fleet of 25 corporate smartphones fully set up with active enterprise security profiles in a matter of 48 hours. MobiSphere rose to the challenge brilliantly. Not only did they beat all online quotes, but they also delivered every unit labeled, tested, and ready for work. Exemplary support!',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    date: 'April 29, 2026'
  },
  {
    id: 'r3',
    name: 'Emily Watson',
    role: 'Photographer & Designer',
    text: 'I shattered my Galaxy Ultra screen right before a massive weekend wedding shoot. The team at MobiSphere completed a full certified OLED sensory screen swap, re-sealed the chassis for dust & water resistance, and fully tested the optics in under 35 minutes! Genuinely saved my career that afternoon.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
    date: 'June 02, 2026'
  },
  {
    id: 'r4',
    name: 'David Miller',
    role: 'Competitive Mobile Gamer',
    text: 'Fantastic catalog! Selected my ROG Phone accessorized cooling docks directly off their shelves. Pricing is insanely competitive compared to online logistics, and obtaining physical, immediate local warranty validation was the peace of mind I truly needed.',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    date: 'March 15, 2026'
  }
];

export const FAQS: FAQItem[] = [
  {
    id: 'f1',
    question: 'Are all your smartphones genuine and coming with official warranty?',
    answer: 'Absolutely. Every single device sold at MobiSphere is 100% brand new, authentic, and carries the official manufacturer direct warranty (e.g. 1 year Apple Care or Authorized Samsung Shield Warranty). We do not retail gray-market imports or blacklisted devices.',
    category: 'Products'
  },
  {
    id: 'f2',
    question: 'How long does a standard smartphone screen or battery replacement take?',
    answer: 'Our certified hardware technicians perform standard screen swaps and battery replacements in approximately 30 to 45 minutes on-site. We have a dedicated waiting lounge with coffee where you can view your device being repaired through our clean-room window.',
    category: 'Repairs'
  },
  {
    id: 'f3',
    question: 'What is your warranty coverage on diagnostic repairs or component replacements?',
    answer: 'We provide a 180-day premium warranty on all parts replaced and labor associated with your repair. If the exact same issue arises of non-accidental nature during this frame, we fix it again completely free of charge.',
    category: 'Repairs'
  },
  {
    id: 'f4',
    question: 'Can you transfer my WhatsApp and private documents if I switch platforms iOS to Android?',
    answer: 'Yes! We possess industry-grade data migration vaults that transfer your full WhatsApp history (including voice notes and videos), contacts, galleries, notes, and documents in under 15 minutes. No data is saved or cached during this secure, encrypted operation.',
    category: 'Services'
  },
  {
    id: 'f5',
    question: 'Do you offer instant trade-ins for older or damaged devices?',
    answer: 'We certainly do. Bring in your existing handset for a comprehensive 5-minute automated diagnostic checklist. We offer highly competitive physical evaluations which can be applied directly as instant cash value discounts toward your new gadget.',
    category: 'Products'
  }
];
